apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
  labels:
    app: transfer-service
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: transfer-service
      spec:
        containers:
          - name: transfer-service
            image: banking/transfer-service:latest
            ports:
              - containerPort : 8084
            env : 
             - name : SPRING_DATASOURCE_URL
               value: jdbc:postgresql://postgres:5432/transfer_db
             - name : SPRING_KAFKA_BOOTSTRAP_SERVERS
               value: kafka:9092
             - name : SPRING_DATA_REDIS_HOST
               value: redis
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"

---
apiVersion: v1
kind : Service
metadata: 
  name: transfer-service
spec:
  selector:
    app: transfer-service
  ports:
    -port : 8084
    targetPort: 8084
  type: ClusterIP
